baseURL = 'https://icarus.project/'
title = 'Icarus Project'

defaultContentLanguage = "en"
languageCode = 'en-us'

rssLimit  = 300
copyright = "Some rights reserved. Unless otherwise noted, content on this page is under a Creative Commons license."

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = true

pluralizeListTitles = false
paginate = 8

[author]
  name = "Icarus Project"
  email = "info@fightcensorship.tech"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

 # Metadata mostly used in document's head
  description = ""
  keywords = ""
  images = ["img/default.png"]

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/icaruslab/icaruslab.github.io/commit/"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  justifyContent = false

   # Colors for favicons
  [params.favicon.color]
    mask = "#328378"
    msapplication = "#328378"

  # Social icons
  [[params.social]]
    name = "facebook"
    url  = "https://www.facebook.com/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/icaruslab"

[languages]
  [languages.en]
    subtitle  = ""
    weight    = 1
    copyright = 'Icarus Project, Inc. All rights reserved.'
  [[languages.en.menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = "1"
  [[languages.en.menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = "2"
  [[languages.en.menu.main]]
    identifier = "documentation"
    name       = "Documentation"
    url        = "/documentation/"
    weight     = "3"
  [[languages.en.menu.main]]
    identifier = "community"
    name       = "Community"
    url        = "/community/"
    weight     = "4"
#  [[languages.en.menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "/blog/"
#    weight     = "5"
  [[languages.en.menu.footer]]
    identifier = "community"
    name       = "Community"
    url        = "/community/"
    weight     = "1"

[privacy]
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true